<?php
include_once('OAuth.php');

//pesapal params
$token = $params = NULL;

/*
PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
when you are ready to go live change to https://www.pesapal.com.
*/
$consumer_key = '0ZZNnQ/6Ep9BORk5euqrz11We9INV4Bg';//Register a merchant account on
                   //demo.pesapal.com and use the merchant key for testing.
                   //When you are ready to go live make sure you change the key to the live account
                   //registered on www.pesapal.com!
$consumer_secret = 'gNbsFQt8OxVkqNfyHMYG/uc15n0=';// Use the secret from your test
                   //account on demo.pesapal.com. When you are ready to go live make sure you 
                   //change the secret to the live account registered on www.pesapal.com!
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = 'https://www.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!
                   // http://demo.pesapal.com/  for demo

//get form details
$amount = $_POST['amount'];
$amount = number_format($amount, 2);//format amount to 2 decimal places

$desc = $_POST['description'];
$type = $_POST['type']; //default value = MERCHANT
$reference = $_POST['reference'];//unique order id of the transaction, generated by merchant
$first_name = $_POST['first_name'];
$last_name = $_POST['last_name'];
$email = $_POST['email'];
$phonenumber = '';//ONE of email or phonenumber is required

$callback_url = 'http://www.yourdomain.com/redirect.php'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src
?>

<!DOCTYPE html>
<html lang="en">
<head prefix="og: https://ogp.me/ns# fb: http://ogp.me/ns/fb# ondango: https://ogp.me/ns/fb/ondango#">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><link href="/shop/favicon.ico" type="image/x-icon" rel="icon" /><link href="/shop/favicon.ico" type="image/x-icon" rel="shortcut icon" /><meta name="robots" content="noindex,nofollow" /><meta property="fb:app_id" content="172876086066223" /><title>SSL Secure Shop</title>
	<link rel="stylesheet" type="text/css" href="https://static.ondango.com/css/flexslider.css" />
	<link rel="stylesheet" type="text/css" href="https://static.ondango.com/css/screen.css?18" />
	<script type="text/javascript" src="/shop/js/config.js"></script>
	<script type="text/javascript" src="https://static.ondango.com/js/ondango_v4_libs.js?3"></script>
	<script type="text/javascript" src="https://static.ondango.com/js/ondango_v4.js?24"></script>
	<!--[if IE]><script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->	<!--[if lt IE 9]>
	<link rel="stylesheet" type="text/css" href="https://static.ondango.com/css/ie" />
<![endif]-->
</head>
<body>

<div id="fb-root"></div>
<script type="text/javascript">
//<![CDATA][
	// Facebook
	window.fbAsyncInit = function () {
		FB.init ({
			appId: 172876086066223,
			status: true,
			cookie: true,
			oauth: true,
			channelUrl: "https://www.ondango.com/shop/app/webroot/channel1.html",
			xfbml: true
		});

		FB.Canvas.setSize ();
	};

	(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s);js.id = id;
		js.src = "//1connect.facebook.net/en_US/all.js";
		fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk')
	);
//]]>
</script>

<div id="main_container">
	<div id="site">
		<header>

			
		<section class="header small">
		<a href="/shop/bobble-shop" id="shop-logo" class="js-loading"><div class="mask-box"><img src="https://graph.facebook.com/393656630668109/picture?type=large" alt="bobble shop - Logo" /></div></a>
		<div class="title">
			<h1>bobble shop</h1>

						<p>Cart</p>
					</div>

	
		
<div class="go-to-cart">
	
	
	</div> <!-- /.go-to-cart -->

		<div class="clr"><!-- --></div>
	</section> <!-- /.header -->
</header>

<nav>
	<ul>
<li><a href="/upload/shop/bobble-shop" class="js-loading">Home</a></li>
<li class="separator"><!-- --></li>
<li><a href="/upload/shop/cart.php" class="js-loading">1. Cart</a></li>
<li class="separator"><!-- --></li><li style="color:#3B5998;">2. Payment method</li>
<li class="separator"><!-- --></li><li>3. Review order</li>
<li class="separator"><!-- --></li><li>4. Confirmation</li>	
          </ul>
	<div class="clr"><!-- --></div>
</nav>

	<div class="fan-discount-banner">
		<div class="icon"><!-- --></div>
		<div class="inner-box small">
			<h6>Special fan discount!</h6>

			<p id="fanDiscountMsg">
				<span id="fanDiscountDynMsg">
								Click on the Like button to become a fan and get 10% off on your purchase. 
								</span>

								Hurry up, only the next 1 buyers will get the discount!							</p>
		</div>

		<div class="call-to-action">
			<div>
							<div class="fb-like" 
					data-href="http://www.facebook.com/bobblegermany" 
					data-send="false" 
					data-layout="button_count" 
					data-width="90" 
					data-show-faces="false" 
					data-font="lucida grande">
				</div>
						</div>
		</div>

		<div class="clr"><!-- --></div>
	</div> <!-- /.fan-discount-banner -->


<section class="checkout">
	<div class="fb-box">
		<div class="fb-box-header cart">
			<h1>Your order</h1>
			<p>Cart</p>
			<em></em>
		</div>

		<div class="fb-box-inner">

			            						<div class="product first-elem">
							
							<div class="title">
	<!--<a href="" class="js-loading"><a>-->								
<br />

															</div>
<!--i frame goes here-->
<iframe src="<?php echo $iframe_src;?>" width="100%" height="620px"  scrolling="no" frameBorder="0">
	<p>Browser unable to load iFrame</p>
</iframe>
<!--i frame goes here end-->
</div>
						</div>
													
					</div>									
			
				
									<!--<form id="coupon-box" class="default" method="post" action="/shop/cart/redeem-coupon" accept-charset="utf-8">
									<div style="display:none;"><input type="hidden" name="_method" value="POST" /></div>				
									<input type="hidden" name="data[Shop][slug]" value="bobble-shop" id="ShopSlug" />					
									<input name="data[Shop][coupon_discount_code]" type="text" maxlength="12" id="ShopCouponDiscountCode" />				
									<input class="button light small" type="submit" value="Redeem coupon" />
					<div id="coupon-message"></div>
				</form>-->			</div>
                        

		<div class="button-box">
			<!--<a href="/upload/shop/product/bobble-shop/17193/bobble-brush-pink.htm" class="button light left js-loading">Continue shopping</a>-->		
			<!--<a href="/upload/shop/shoping_cart_form.php" class="button js-loading">Pesapal</a>		
			</div>-->
	</div> <!-- /.fb-box (Cart) -->


	<!--<div id="recommendations-box" data-shop-slug="bobble-shop" class="loading-content"></div>-->
</section>




<footer>
	<ul class="seals">
	
		<li><span class="ssl-icon" title="SSL Secure Shop">SSL Secure Shop</span></li>
	</ul>
	
	
	<ul class="navi">
	<li><a href="#imprint" class="legal-btn">Imprint</a></li><li>�</li><li><a href="#privacy_policy" class="legal-btn">Privacy Policy</a></li><li>�</li>	
	<li><a href="#shipping-details" class="shipping-btn-footer">Shipping</a></li>
	</ul>

		<ul class="ondango">
		<li>
			<span>Powered by:</span>
			Ondango - Your online shop on Facebook
		</li>
		<li><a href="http://www.ondango.com?ref=shop-footer" target="_blank">Create your own Shop</a></li>
	</ul>
	</footer>

		<div class="clr"><!-- --></div>
	</div>

	<div id="fb-loading-box">
		<p>Please wait while we process your order...</p>
	</div>

	</div>





	<script type="text/javascript" src="https://static.ondango.com/js/webtrekk_v3.js"></script>
<script type="text/javascript">
//<![CDATA][

	// Google analytics
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-21629519-1']);
	_gaq.push(['_trackPageview']);
	_gaq.push(['_anonymizeIp']);

	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
//]]>
</script>

		
	
	<script type="text/javascript">
//<![CDATA[

			var pageConfig = {
				linkTrack:	"link",		// Activate Link Tracking [link or standard]
				heatmap:	"0",		// Activate Heatmap Tracking [1 = on | 0 = off]
				form:		"1",		// Activate Form Tracking [1 = on | 0 = off]
				contentId:	""
			};
			var wt = new webtrekkV3( pageConfig );
			
			

			wt.sendinfo( {"contentId":"Ondango.bobble-shop.checkout.1-cart","contentGroup":{"1":"bobble-shop","2":"checkout","10":"1-cart"}} );
		
//]]>
</script>
	<noscript><div><img src="http://q3.webtrekk.net/980157259404316/wt.pl?p=322,0" height="1" width="1" alt="" /></div></noscript>
</body>
</html>



---------------------------------

